on:
  issues:
    types: [opened, closed, reopened]

permissions: write-all

env:
  GITHUB_API_TOKEN: ${{ secrets.ACTION_TOKEN }}
#            "#{{ secrets.GITHUB_TOKEN }}"

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Assign new issues to the project
        uses: ./
        with:
          project_url: "https://github.com/orgs/mapbox/projects/707"
